CREATE TABLE gallery_picture (
    id BIGSERIAL PRIMARY KEY,
    url VARCHAR(1024),
    storage_key VARCHAR(512),
    thumbnail_url VARCHAR(1024),
    thumbnail_storage_key VARCHAR(512),
    name VARCHAR(255) NOT NULL,
    introduction TEXT,
    category VARCHAR(64),
    tags JSONB,
    pic_size BIGINT,
    pic_width INTEGER,
    pic_height INTEGER,
    pic_scale DOUBLE PRECISION,
    pic_format VARCHAR(32),
    user_id BIGINT NOT NULL DEFAULT 1,
    space_id BIGINT NOT NULL DEFAULT 0,
    review_status INTEGER NOT NULL DEFAULT 1,
    pic_color VARCHAR(64),
    source_type VARCHAR(64),
    favorited BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMP NOT NULL DEFAULT now(),
    update_time TIMESTAMP NOT NULL DEFAULT now(),
    is_delete INTEGER NOT NULL DEFAULT 0
);
